name: MehranHaghirian
favicon: null
layout_spectrum: 1
typography_spectrum: 1
title: Mehran Haghirian
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#9D2D3C'
    - '#DDE4DD'
    - '#BCAB47'
    - '#6B574B'
    - '#160600'
  brandStrength: 0.9408670626580715
  lightness: 0.8908052421174943
  saturation: 0.2538611744530499
  rhythmicContrast: 0.34941720264032483
purpose: []
